### ISSUE TITLE
[PE-D][Tester C] Add: Timestamp cannot be in the future

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-T14-2/tp#100]
Even though it is not stated in the documentation, the `add` command will not allow you to add a pet if its timestamp is in the future.

Relevant section of documentation:
![image.png](https://raw.githubusercontent.com/filbertphang/ped/main/files/fc2fd10c-2748-4e6b-b393-eecbd4df0f4e.png)

sample input: `add o/Alice n/Doggo p/98765432 e/example@gmail.com a/311, Clementi Ave 2, #02-25 ts/2024-03-31 14:48:09 t/Dog t/Chihuahua`

This may be classified as a documentation or a functionality bug, depending on whether this behaviour is intended or not

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: filbertphang/ped#6

**Comment by wengkit1** [comment]
Thanks for raising this issue to us.

**Comment by YuanXun9834** [comment]
Fixed
