### ISSUE TITLE
[PE-D][Tester D] Missing Table of Contents in User Guide

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-T14-2/tp#83]
The user guide is missing the Table of Contents which is very important for a user to get a glance of the document as well as to be able to navigate easily
![TOC.png](https://raw.githubusercontent.com/vsamarth/ped/main/files/4f2c66a2-c7a7-4aca-81ee-ba5fd937197a.png)

-------------
Labels: `type.DocumentationBug` `severity.Medium`
original: vsamarth/ped#2

**Comment by YuanXun9834** [comment]
Fixed
