### ISSUE TITLE
[PE-D][Tester C] UG: Wrong add command syntax for deadline field

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-T14-2/tp#95]
UG says deadline should be a date formatted as such:
![image.png](https://raw.githubusercontent.com/filbertphang/ped/main/files/940fa614-5ad1-4f75-8e92-246cc1b98500.png)

But the example given (also in the UG) shows that the deadline has an additional "name" portion to it (the `Feed dog - ...` part)

![image.png](https://raw.githubusercontent.com/filbertphang/ped/main/files/fb37f1f2-51cb-4932-8b50-5f00293f4e57.png)

Similarly, the parameters for the `add` command are also inconsistent in the help text in the app (does not include timestamp, deadline, etc):

![image.png](https://raw.githubusercontent.com/filbertphang/ped/main/files/e198e845-d08c-4ae3-a9cf-95bcbf2dd0c8.png)

![image.png](https://raw.githubusercontent.com/filbertphang/ped/main/files/dd2dd902-940a-4c13-8baa-dfc589d23775.png)

-------------
Labels: `type.DocumentationBug` `severity.Medium`
original: filbertphang/ped#5

**Comment by YuanXun9834** [comment]
Tester misread, the table shown is constraints for deadlines not the format of inputting deadlines.
