### ISSUE TITLE
[PE-D][Tester D] `changecost` does not seem to do anything

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-T14-2/tp#96]
Even after changing cost for a pet to very high which should change the value, the cost for a pet is not changed in the UI.

<i><video controls><source src="https://raw.githubusercontent.com/vsamarth/ped/main/files/d59be9e7-ba0a-4a40-989b-efcb28e0800c.mov" type="video/mp4">Your browser does not support the video tag.</video><br>video:https://raw.githubusercontent.com/vsamarth/ped/main/files/d59be9e7-ba0a-4a40-989b-efcb28e0800c.mov</i>

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: vsamarth/ped#8

**Comment by YuanXun9834** [comment]
Cost is updated on click which we failed to mention in the UG
